spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: username
    password: password
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
digital-wallet:
  url: localhost
smart-money:
  url: localhost